---
ActionAtoms:
  backward:
    ui_accessibilityId: 返回上一级
    ui_action: click

  backward in webview:
    ui_accessibilityId: web返回上一级
    ui_action: click

  close webview:
    ui_name: 关闭
    ui_action: click

  return homepage:
    ui_accessibilityId: 回到首页
    ui_action: click

  swipe down:
    ui_action: swipe
    data:
      startX: 275
      startY: 700
      offsetX: 0
      offsetY: -500
      duration: 400

  get orderId:
    ui_xpath: //XCUIElementTypeApplication[1]/XCUIElementTypeWindow[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeTable[1]/XCUIElementTypeCell[4]/XCUIElementTypeStaticText[5]
    ui_action: getValue

  fake pay:
    ui_action: pay
    data:
      url: http://shopappserver.showjoy.net/Fake_Pay?orderNumber={{idid}}
      headers:
        cookie:
          tgc=bsK6KS0wQi;um_remember="5385980EA93F8265018C9FCD285B8ED7:2E175E4D7F73DDD96CC2524B965E12A6:CC1F08AA5F8A0FA68B8D3532EA3C68AC";

  fake pay1:
      ui_action: net
      data:
        url: http://shopappserver.showjoy.net/Fake_Pay
        qs:
          orderNumber: {{idid}}
        headers:
          cookie:
            tgc=bsK6KS0wQi;um_remember="5385980EA93F8265018C9FCD285B8ED7:2E175E4D7F73DDD96CC2524B965E12A6:CC1F08AA5F8A0FA68B8D3532EA3C68AC";
          x-requst: {{requestId}}
